<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create 2 admin accounts first
        $superAdmin = User::create([
            'name' => 'Super Admin Servify',
            'email' => 'superadmin@servify.com',
            'password' => Hash::make('Admin@123'),
            'phone' => '081100000001',
            'role' => 'super_admin',
            'rating' => 5.0,
            'completed_jobs' => 0,
            'completed_sos' => 0,
            'helped_sos' => 0,
            'total_points' => 0,
            'total_earnings' => 0,
            'is_verified' => true,
            'current_latitude' => -6.191100,
            'current_longitude' => 106.821900,
            'current_address' => 'Servify HQ - Jakarta, Indonesia',
            'address' => 'Jl. Sudirman No. 1, Jakarta Pusat',
            'nik' => '3201010101010001',
            'date_of_birth' => '1985-01-01',
            'gender' => 'male',
        ]);

        $operationsAdmin = User::create([
            'name' => 'Operations Admin',
            'email' => 'admin@servify.com',
            'password' => Hash::make('Admin@123'),
            'phone' => '081100000002',
            'role' => 'admin',
            'rating' => 4.9,
            'completed_jobs' => 12,
            'completed_sos' => 4,
            'helped_sos' => 2,
            'total_points' => 900,
            'total_earnings' => 2400000,
            'is_verified' => true,
            'current_latitude' => -6.190800,
            'current_longitude' => 106.823200,
            'current_address' => 'Servify Operation Center - Jakarta',
            'address' => 'Jl. Thamrin No. 10, Jakarta Pusat',
            'nik' => '3201010101010002',
            'date_of_birth' => '1990-05-15',
            'gender' => 'male',
        ]);

        // Create 15 regular users with complete data
        $users = [
            [
                'name' => 'Ahmad Rizki',
                'email' => 'ahmad@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567890',
                'role' => 'user',
                'rating' => 4.8,
                'completed_jobs' => 15,
                'completed_sos' => 2,
                'helped_sos' => 5,
                'total_points' => 1500,
                'total_earnings' => 2250000,
                'is_verified' => true,
                'current_latitude' => -6.200000,
                'current_longitude' => 106.816666,
                'current_address' => 'Jakarta Selatan, Indonesia',
                'address' => 'Jl. Sudirman No. 123, Jakarta Selatan',
                'nik' => '3201010101010003',
                'date_of_birth' => '1995-03-20',
                'gender' => 'male',
            ],
            [
                'name' => 'Sarah Wilson',
                'email' => 'sarah@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567891',
                'role' => 'user',
                'rating' => 4.9,
                'completed_jobs' => 45,
                'completed_sos' => 8,
                'helped_sos' => 12,
                'total_points' => 3400,
                'total_earnings' => 6750000,
                'is_verified' => true,
                'current_latitude' => -6.201000,
                'current_longitude' => 106.817000,
                'current_address' => 'Jakarta Pusat, Indonesia',
                'address' => 'Jl. Thamrin No. 456, Jakarta Pusat',
                'nik' => '3201010101010004',
                'date_of_birth' => '1992-07-10',
                'gender' => 'female',
            ],
            [
                'name' => 'Mike Johnson',
                'email' => 'mike@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567892',
                'role' => 'user',
                'rating' => 4.7,
                'completed_jobs' => 32,
                'completed_sos' => 5,
                'helped_sos' => 8,
                'total_points' => 2200,
                'total_earnings' => 4800000,
                'is_verified' => true,
                'current_latitude' => -6.202000,
                'current_longitude' => 106.818000,
                'current_address' => 'Jakarta Utara, Indonesia',
                'address' => 'Jl. Gatot Subroto No. 789, Jakarta Utara',
                'nik' => '3201010101010005',
                'date_of_birth' => '1988-11-25',
                'gender' => 'male',
            ],
            [
                'name' => 'Lisa Brown',
                'email' => 'lisa@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567893',
                'role' => 'user',
                'rating' => 4.5,
                'completed_jobs' => 8,
                'completed_sos' => 1,
                'helped_sos' => 2,
                'total_points' => 600,
                'total_earnings' => 1200000,
                'is_verified' => false,
                'current_latitude' => -6.203000,
                'current_longitude' => 106.819000,
                'current_address' => 'Jakarta Barat, Indonesia',
                'address' => 'Jl. Kemang Raya No. 321, Jakarta Barat',
                'nik' => '3201010101010006',
                'date_of_birth' => '1998-02-14',
                'gender' => 'female',
            ],
            [
                'name' => 'David Lee',
                'email' => 'david@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567894',
                'role' => 'user',
                'rating' => 4.6,
                'completed_jobs' => 28,
                'completed_sos' => 4,
                'helped_sos' => 7,
                'total_points' => 1800,
                'total_earnings' => 4200000,
                'is_verified' => true,
                'current_latitude' => -6.204000,
                'current_longitude' => 106.820000,
                'current_address' => 'Jakarta Timur, Indonesia',
                'address' => 'Jl. Pondok Indah No. 654, Jakarta Timur',
                'nik' => '3201010101010007',
                'date_of_birth' => '1991-09-30',
                'gender' => 'male',
            ],
            [
                'name' => 'Emma Davis',
                'email' => 'emma@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567895',
                'role' => 'user',
                'rating' => 4.9,
                'completed_jobs' => 12,
                'completed_sos' => 3,
                'helped_sos' => 4,
                'total_points' => 890,
                'total_earnings' => 1800000,
                'is_verified' => true,
                'current_latitude' => -6.205000,
                'current_longitude' => 106.821000,
                'current_address' => 'Depok, Indonesia',
                'address' => 'Jl. Bintaro Raya No. 987, Depok',
                'nik' => '3201010101010008',
                'date_of_birth' => '1994-04-18',
                'gender' => 'female',
            ],
            [
                'name' => 'Alex Chen',
                'email' => 'alex@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567896',
                'role' => 'user',
                'rating' => 4.8,
                'completed_jobs' => 38,
                'completed_sos' => 6,
                'helped_sos' => 10,
                'total_points' => 2500,
                'total_earnings' => 5700000,
                'is_verified' => true,
                'current_latitude' => -6.206000,
                'current_longitude' => 106.822000,
                'current_address' => 'Tangerang, Indonesia',
                'address' => 'Jl. Bekasi Raya No. 147, Tangerang',
                'nik' => '3201010101010009',
                'date_of_birth' => '1989-12-05',
                'gender' => 'male',
            ],
            [
                'name' => 'Maria Garcia',
                'email' => 'maria@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567897',
                'role' => 'user',
                'rating' => 4.7,
                'completed_jobs' => 25,
                'completed_sos' => 3,
                'helped_sos' => 6,
                'total_points' => 1750,
                'total_earnings' => 3750000,
                'is_verified' => true,
                'current_latitude' => -6.207000,
                'current_longitude' => 106.823000,
                'current_address' => 'Bekasi, Indonesia',
                'address' => 'Jl. Senayan No. 258, Bekasi',
                'nik' => '3201010101010010',
                'date_of_birth' => '1993-06-22',
                'gender' => 'female',
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567898',
                'role' => 'user',
                'rating' => 4.6,
                'completed_jobs' => 20,
                'completed_sos' => 2,
                'helped_sos' => 5,
                'total_points' => 1400,
                'total_earnings' => 3000000,
                'is_verified' => true,
                'current_latitude' => -6.208000,
                'current_longitude' => 106.824000,
                'current_address' => 'Jakarta Selatan, Indonesia',
                'address' => 'Jl. Kuningan No. 369, Jakarta Selatan',
                'nik' => '3201010101010011',
                'date_of_birth' => '1990-08-12',
                'gender' => 'male',
            ],
            [
                'name' => 'Siti Nurhaliza',
                'email' => 'siti@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567899',
                'role' => 'user',
                'rating' => 4.9,
                'completed_jobs' => 50,
                'completed_sos' => 10,
                'helped_sos' => 15,
                'total_points' => 3800,
                'total_earnings' => 7500000,
                'is_verified' => true,
                'current_latitude' => -6.209000,
                'current_longitude' => 106.825000,
                'current_address' => 'Jakarta Pusat, Indonesia',
                'address' => 'Jl. Sudirman No. 500, Jakarta Pusat',
                'nik' => '3201010101010012',
                'date_of_birth' => '1987-01-15',
                'gender' => 'female',
            ],
            [
                'name' => 'Rudi Saputra',
                'email' => 'rudi.banned@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081277788899',
                'role' => 'user',
                'rating' => 4.2,
                'completed_jobs' => 6,
                'completed_sos' => 0,
                'helped_sos' => 1,
                'total_points' => 320,
                'total_earnings' => 900000,
                'is_verified' => false,
                'current_latitude' => -6.210000,
                'current_longitude' => 106.825000,
                'current_address' => 'Jakarta Selatan, Indonesia',
                'address' => 'Jl. Fatmawati No. 100, Jakarta Selatan',
                'nik' => '3201010101010013',
                'date_of_birth' => '1996-03-08',
                'gender' => 'male',
                'is_banned' => true,
                'ban_started_at' => Carbon::now()->subDays(2),
                'banned_until' => Carbon::now()->addDays(5),
                'ban_reason' => 'Pelanggaran ketentuan komunitas (penipuan pembayaran).',
                'last_banned_by' => $operationsAdmin->id,
            ],
            [
                'name' => 'Indah Permata',
                'email' => 'indah@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567900',
                'role' => 'user',
                'rating' => 4.4,
                'completed_jobs' => 5,
                'completed_sos' => 0,
                'helped_sos' => 0,
                'total_points' => 250,
                'total_earnings' => 750000,
                'is_verified' => false,
                'current_latitude' => -6.211000,
                'current_longitude' => 106.826000,
                'current_address' => 'Jakarta Barat, Indonesia',
                'address' => 'Jl. Daan Mogot No. 200, Jakarta Barat',
                'nik' => '3201010101010014',
                'date_of_birth' => '1999-05-20',
                'gender' => 'female',
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567901',
                'role' => 'user',
                'rating' => 4.8,
                'completed_jobs' => 35,
                'completed_sos' => 7,
                'helped_sos' => 9,
                'total_points' => 2400,
                'total_earnings' => 5250000,
                'is_verified' => true,
                'current_latitude' => -6.212000,
                'current_longitude' => 106.827000,
                'current_address' => 'Tangerang, Indonesia',
                'address' => 'Jl. BSD Raya No. 300, Tangerang',
                'nik' => '3201010101010015',
                'date_of_birth' => '1992-10-28',
                'gender' => 'male',
            ],
            [
                'name' => 'Dewi Lestari',
                'email' => 'dewi@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567902',
                'role' => 'user',
                'rating' => 4.7,
                'completed_jobs' => 18,
                'completed_sos' => 2,
                'helped_sos' => 4,
                'total_points' => 1200,
                'total_earnings' => 2700000,
                'is_verified' => true,
                'current_latitude' => -6.213000,
                'current_longitude' => 106.828000,
                'current_address' => 'Depok, Indonesia',
                'address' => 'Jl. Margonda Raya No. 400, Depok',
                'nik' => '3201010101010016',
                'date_of_birth' => '1995-11-12',
                'gender' => 'female',
            ],
            [
                'name' => 'Fajar Pratama',
                'email' => 'fajar@example.com',
                'password' => Hash::make('password123'),
                'phone' => '081234567903',
                'role' => 'user',
                'rating' => 4.5,
                'completed_jobs' => 10,
                'completed_sos' => 1,
                'helped_sos' => 3,
                'total_points' => 700,
                'total_earnings' => 1500000,
                'is_verified' => true,
                'current_latitude' => -6.214000,
                'current_longitude' => 106.829000,
                'current_address' => 'Bekasi, Indonesia',
                'address' => 'Jl. Ahmad Yani No. 500, Bekasi',
                'nik' => '3201010101010017',
                'date_of_birth' => '1997-07-03',
                'gender' => 'male',
            ],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }
    }
}
